#!/bin/bash
BUILD=${1:-"build-asan"}
SOURCE=${2:-"~/src/arangodb/arangodb"}
(cd $BUILD && CC=/usr/lib/ccache/gcc-9 CXX=/usr/lib/ccache/g++-9 CXXFLAGS="-fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fsanitize=leak -fno-sanitize=alignment -fno-sanitize=vptr" nice -n 10 cmake $SOURCE -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_JEMALLOC=Off -DUSE_ENTERPRISE=On -DUSE_MAINTAINER_MODE=On -DUSE_FAILURE_TESTS=On -DUSE_BACKTRACE=On -DUSE_STRICT_OPENSSL_VERSION=Off)
echo -e "\a"
