#!/bin/bash

VERSION=$1

git checkout v$VERSION && (cd enterprise && git checkout v$VERSION) && mkdir build-$VERSION && (cd build-$VERSION && ~/work/scripts/build-enterprise . && rm -rf 3rdParty/ arangod arangosh lib tests)

echo -e '\a'
