#!/bin/bash

VERSION=$1

git checkout v$VERSION && \
    mkdir build-$VERSION && \
    (cd build-$VERSION && ~/work/scripts/build-community .) && \
    ~/work/scripts/make-desktop build-$VERSION && \
    (cd build-$VERSION && rm -rf 3rdParty/ arangod arangosh lib tests)

echo -e '\a'
